version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    environment:
      CODECOV_TOKEN: "c694484c-c0bd-4254-a341-92de61fa0e31"
    steps:
    - checkout
    - run:
        command: |
          go mod download
          go build ./...
          go test -coverprofile=coverage.txt -covermode=count ./...
          bash <(curl -s https://codecov.io/bash)
#  build110:
#    docker:
#      - image: circleci/golang:1.10
#    environment:
#      GO_VENDOR_EXPERIMENT: 1
#    steps:
#      - checkout
#      -run :
#        command: |
#          vgo mod download
#          vgo build ./...
#          vgo test ./...
#workflow:
#  build:
#    jobs:
#      - build
#      - build110
